ignore:
  - "pkg/cli/**"
  - "pkg/device/**"
  - "pkg/emulator/**"
  - "pkg/simulator/**"
  - "pkg/jsengine/**"
  - "pkg/logger/**"
  - "pkg/driver/wda/runner.go"
  - "pkg/driver/wda/setup.go"
  - "pkg/driver/devicelab/webview.go"
  - "pkg/driver/devicelab_ios/**"
